In [1]:
#grande quantidade de dados se assemelha a lista mas tem mais "poder"
#numpy é escrito em C

In [2]:
import numpy as np

In [3]:
minha_lista = [1,2,3,4]

In [4]:
minha_lista

[1, 2, 3, 4]

In [6]:
arr = np.array(minha_lista)

In [13]:
arr[-1]

4

In [14]:
for i in arr:
    print(i)

1
2
3
4


In [15]:
type(arr)

numpy.ndarray

In [17]:
minha_matriz = [[1,2,3],[4,5,6],[7,8,9]]

In [18]:
minha_matriz

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [19]:
m = np.array(minha_matriz)

In [20]:
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
m[2][:2]

array([7, 8])

In [28]:
v = list(range(10))

In [29]:
v

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [30]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
np.zeros(3)

array([0., 0., 0.])

In [32]:
x =np.zeros((12,4))

In [34]:
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [35]:
x.shape

(12, 4)

In [37]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [39]:
np.ones((5,5,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [41]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [42]:
x = np.array(minha_matriz)

In [43]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
#ver a ordem da matriz
x.shape

(3, 3)

In [45]:
x.max()

9

In [46]:
x.min()

1

In [47]:
x.argmax()

8

In [48]:
x.argmin()

0

In [49]:
x2 = np.array([[5,6,1],[8,7,9],[2,4,3]])

In [53]:
x2

array([[5, 6, 1],
       [8, 7, 9],
       [2, 4, 3]])

In [52]:
x2.argmax()

5

In [54]:
arr = np.arange(0,30,3)

In [55]:
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [56]:
arr[3:7]

array([ 9, 12, 15, 18])

In [57]:
arr[2:6] = 0

In [60]:
arr.shape

(10,)

In [61]:
#reshape(linhas,colunas)
arr2 = np.arange(50).reshape(5,10)

In [62]:
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [63]:
arr2.shape

(5, 10)

In [64]:
arr2[:3][2][1]

21

In [67]:
arr2[:3][2][1]

21

In [ ]:
#ponteiro

In [68]:
v = [1,2,3,4]

In [69]:
v2 = v

In [76]:
v

[0, 99999, 3, 4]

In [77]:
v2

[0, 99999, 3, 4]

In [73]:
v2

[0, 2, 3, 4]

In [78]:
v2 = v.copy()

In [79]:
v2[-1] = 1000

In [80]:
v2

[0, 99999, 3, 1000]

In [81]:
v

[0, 99999, 3, 4]

In [84]:
#shift + tab para acessar um help resumido de uma função
sum([1,2,3,4],2)

12

In [85]:
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [86]:
arr3 = arr2[:3]

In [87]:
arr3[:] = 100

In [88]:
arr3

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100]])

In [89]:
arr2

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49]])

In [ ]:
#arr3 se torna uma referencia a um pedaço do array 2

In [90]:
arr3 = arr2[:3].copy()

In [91]:
arr3 

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100]])

In [92]:
arr3[:] = 0

In [93]:
arr3

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [94]:
arr2

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49]])

In [96]:
arr2

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49]])

In [95]:
arr2[3:,4:9]

array([[34, 35, 36, 37, 38],
       [44, 45, 46, 47, 48]])

In [97]:
arr2

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49]])

In [100]:
arr2 > 42

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False,  True,  True,  True,  True,  True,  True,
         True]])

In [101]:
arr = np.arange(0,16)

In [102]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [106]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [107]:
arr + 3

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18])

In [108]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225])

In [109]:
arr / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5])

In [110]:
arr / 0

C:\Users\Bruno.Miura\AppData\Local\Continuum\anaconda\envs\curso_python\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\Users\Bruno.Miura\AppData\Local\Continuum\anaconda\envs\curso_python\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
       inf, inf, inf])

In [111]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335])

In [112]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06])

In [113]:
np.sum(arr)

120

In [114]:
arr.sum()

120

In [115]:
#média
np.mean(arr)

7.5

In [117]:
#desvio padrão
np.std(arr)

4.6097722286464435

In [123]:
arr2 = np.arange(16).reshape(4,4)

In [124]:
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [125]:
#soma as colunas
arr2.sum(axis=0)

array([24, 28, 32, 36])

In [126]:
#soma as linhas
arr2.sum(axis=1)

array([ 6, 22, 38, 54])